### ISSUE TITLE
Can't install on localized Windows 95 OSR2

### ISSUE THREAD

**Issue by winsxspl** [itsmattkc/dotnet9x#8]
Hello, here is the problem:

![Screenshot 2024-04-12 000956](https://github.com/itsmattkc/dotnet9x/assets/21989798/34881a23-6f06-4f8b-99bb-779badb3681b)

and then whole OS hangs and didn't respond to any clicks.

Windows 95 OSR2.1 Polish + USB Supplement Patch + IE 5.01 PL are installed, as you said.
I don't know that error depends on VBox or my localized Polish version of Windows, but I tried three times with the same result. I can't test it on real hardware, because I have only modern machines. Did I something wrong or can you reproduce error with your setup?

My host is a HP notebook with Ryzen 5500U + Windows 11. I gave that VM 64 MB of RAM and all others are set to VBox default values for Windows 95.

**Comment by winsxspl** [comment]
And if you need files to test:
Win95 OSR2.1 + USB Supplement: https://winworldpc.com/download/c39e3567-1d6a-1a11-c3a6-e280947e5254
IE 5.01: https://ia800306.us.archive.org/view_archive.php?archive=/9/items/ks-extra-1-2000/KS%20Extra%201_2000.iso - whole folder 'programy/internetowe/przegladarki/ie501pl'

**Comment by itsmattkc** [comment]
I've found that this can happen with modern virtual machines (e.g. VMware, VirtualBox, QEMU), seemingly because they simply run too fast (even with patcher9x installed). I've had a lot more luck with PCem, which more accurately emulates the speed of computers back then (or of course hardware from the era).

Alternatively, I've found that it helps to install dotnet9x _before_ installing the USB supplement - something about the way VMM32.VXD is patched I guess?

If you can, try either of those and see if that fixes it. If so, perhaps it should be added to the README.

**Comment by VideoGameSmash12** [comment]
Could it be the result of CPU bugs instead? I remember Windows 98 wouldn't install (let along behave) correctly even in a VM on a computer with a Ryzen 7 processor from like 2018 because of some underlying bug with the CPU itself.

![image](https://github.com/itsmattkc/dotnet9x/assets/8041766/ff12e08b-25ec-4991-b299-dc2a9865da79)

**Comment by itsmattkc** [comment]
In theory, patcher9x should resolve those, but it could still be related - I'm not knowledgeable enough to know.

**Comment by winsxspl** [comment]
Thanks. With some fiddling with files I was able to run old version of nLite (req: .NET 1.1) under Windows 95.
Of course with PCem.
Good job!
![Screenshot from 2024-04-12 17-03-09](https://github.com/itsmattkc/dotnet9x/assets/21989798/04e4cb3f-bdeb-4936-a605-38ae36b64453)
